name: Makefile CI

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release"
        required: false
        type: boolean
      version:
        description: "Version number for the release (e.g., 1.0.0)"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    # 👇 Add this block so the workflow can create releases
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsmpartsfinder
          path: builds/dsmpartsfinder

      - name: Create Release
        if: inputs.release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: Automated release
          files: builds/dsmpartsfinder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
